config/routes.rb
Rails.application.routes.draw do
  resources :leads do
    member do
      put 'update_stage'
    end
  end
  root "leads#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord

  def update_stage_without_creating_new(new_stage)
    self.update_columns(stage: new_stage)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @leads = Lead.all
  end

  #PUT /leads/:id/update_stage
  def update_stage
    @lead = Lead.find(params[:id])
    @lead.update_stage_without_creating_new(params[:stage_id])
    render json: {success: true}
  end

  def show
    @lead = Lead.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesallyPipelineDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/leads/index.html.erb
<%= stylesheet_link_tag 'pipeline', media: 'all', 'data-turbolinks-track': 'reload' %>


<div data-controller="pipeline">
  <div class="lists">
    <% stages = ['prospecting', 'qualification', 'need_analysis', 'proposal', 'negotiation', 'closing_deal'] %>
    <% stages.each do |stage| %>
      <h1><%= stage.capitalize %>
      <div class="list" data-stage-id="<%= stage %>" id="<%= stage.capitalize %>">
        <% @leads.select { |lead| lead.stage == stage }.each do |lead| %>
          <div class="list-item" draggable="true" data-lead-id="<%= lead.id %>">
            <%= lead.first_name %>
            <%= lead.email %>
            <%= lead.id %>
            <%= link_to "Lead #{lead.first_name}", lead_path(lead) %>
          </div>
        <% end %>
      </div>
      </h1>
    <% end %>
  </div>
</div>

app/views/leads/show.html.erb
<h1>Lead Details</h1>
<p>First Name: <%= @lead.first_name %></p>
<p>Last Name: <%= @lead.last_name %></p>
<p>Last Name: <%= @lead.stage %></p>